# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Otto < Formula
  desc "Terminal-based MySQL and PostgreSQL client"
  homepage "https://github.com/onurkacmaz/otto"
  version "1.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onurkacmaz/otto/releases/download/v1.3.2/otto_darwin_amd64.tar.gz"
      sha256 "0e7ad6098fca8c9c756280cc992884d6fe0be0c798dd35b544fcf7d007321bf6"

      define_method(:install) do
        bin.install "otto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onurkacmaz/otto/releases/download/v1.3.2/otto_darwin_arm64.tar.gz"
      sha256 "7ac4aa6f516d89f97e194af727438ad4306293d8b8b8dae5bb0b8de8fce03769"

      define_method(:install) do
        bin.install "otto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onurkacmaz/otto/releases/download/v1.3.2/otto_linux_amd64.tar.gz"
      sha256 "d0cec78b1fe07c85ccb9c4654b118ee0a43d17957fbcbd9b3d83f294a814214b"
      define_method(:install) do
        bin.install "otto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onurkacmaz/otto/releases/download/v1.3.2/otto_linux_arm64.tar.gz"
      sha256 "90595f282c07bd0f796b3adb279bf0cba04dbb71fc67239cf0d97ac27678afe7"
      define_method(:install) do
        bin.install "otto"
      end
    end
  end

  test do
    system "#{bin}/otto", "--help"
  end
end
