# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Otto < Formula
  desc "Terminal-based MySQL and PostgreSQL client"
  homepage "https://github.com/onurkacmaz/otto"
  version "1.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onurkacmaz/otto/releases/download/v1.2.3/otto_darwin_amd64.tar.gz"
      sha256 "c2b36b3f497c871746d9d0f0cbe1ff1803262f0092750272af7ad38eb15970ef"

      def install
        bin.install "otto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onurkacmaz/otto/releases/download/v1.2.3/otto_darwin_arm64.tar.gz"
      sha256 "f43eea24cca5db51896dbb6d6f845fbf2d69ae20865ac7dce95f90b67ee03dc7"

      def install
        bin.install "otto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onurkacmaz/otto/releases/download/v1.2.3/otto_linux_amd64.tar.gz"
      sha256 "ce0d2559f8ed198c28bbc4755ceecece481fffd63a36ea672d54cf8f1867a686"
      def install
        bin.install "otto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onurkacmaz/otto/releases/download/v1.2.3/otto_linux_arm64.tar.gz"
      sha256 "e7a4c610b1841cc8f13d124bb8e39b974178f141692745cf0479959b4263d9b6"
      def install
        bin.install "otto"
      end
    end
  end

  test do
    system "#{bin}/otto", "--help"
  end
end
